// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_list_upload from "./routes/api/list-upload.ts";
import * as $index from "./routes/index.tsx";
import * as $item_list from "./islands/item-list.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/list-upload.ts": $api_list_upload,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/item-list.tsx": $item_list,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
